# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Build without Release'
        required: true
        default: 'Build'
      home:
        description: 'location'
        required: false

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn install -T 2C
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.1.4
      with:
      # Artifact name
        name: artifact
        # A file, directory or wildcard pattern that describes what to upload
        path: target
        # The desired behavior if no files are found using the provided path.
